# The ODT Cloud server does not define the [project] table
# as it is not meant for distribution as a package.

# see https://packaging.python.org/en/latest/specifications/dependency-groups/
[dependency-groups]
shared = [
    "celery[redis] >=5.6, <6",
    "pymongo >=4.15, <5",
    "PyYAML >=6, <7",
    "python-dotenv >=1.2, <2",
    "filelock >=3.28, <4",
    "dogpile.cache[redis] >=1.5, <2",
    "requests >=2.32, <3",
    "oligo-designer-toolsuite >=2.1, <2.2",
    "pydantic>=2.12.5,<3",
    "glom>=25.12, <26"
]
server = [
    { include-group = "shared" },
    "Authlib >=1.6, <2",
    "nh3 >=0.3.6, <0.4",
    "Flask >=3.1, <4",
    "flask-cors >=6, <7",
    "Flask-Login >=0.6, <0.7",
    "Flask-Limiter >=4.1, <5",
    "gunicorn >=26, <27",
    "prometheus-flask-exporter >=0.23, <0.24",
    "PyMongo >=4, <5",
]
worker = [{ include-group = "shared" }, "biopython >=1.86, <2"]
test = [
    { include-group = "server" },
    "coverage >=7.12, <8",
    "pytest >=9, <10",
    "pytest-cov >=7, <8",
    "pytest-mock >=3.15, <4",
]
lint = ["pre-commit==4.6", "ruff==0.15.11", "pyrefly==1.1.0"]
types = ["types-Flask-Cors", "types-PyYAML", "types-Authlib", "types-requests"]
dev = [
    { include-group = "server" },
    { include-group = "worker" },
    { include-group = "test" },
    { include-group = "lint" },
    { include-group = "types" },
]

[tool.pytest]
testpaths = ["tests"]

[tool.ruff]
line-length = 110
target-version = "py312"

[tool.ruff.lint]
# Rules that Ruff will apply
# see https://docs.astral.sh/ruff/rules
extend-select = [
    "RUF", # ruff-specific rules
    "UP",  # pyupgrade
    "I",   # isort
]

[tool.pyrefly]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/.*",
    "**/typings",
]
infer-with-first-use = false
preset = "default"
min-severity = "warn"
conda-environment = "odt"
